######################################
######                          ######
######           BOTS           ######
######                          ######
######################################

# Create a bot
mutation CreateBot($input: CreateBotInput!) {
  createBot(input: $input) {
    id
    name
  }
}

# Delete a bot
mutation DeleteBot($input: DeleteBotInput!) {
  deleteBot(input: $input) {
    id
    name
  }
}

# Reset bot api key
mutation ResetApiKey($input: GetBotInput!) {
  resetApiKey(input: $input)
}

# Create a vote, targeting bot
mutation CreateVote($input: BotVoteCreateInput!) {
  createVote(input: $input) {
    botId
    expires
  }
}

# Create a bot webhook
mutation CreateWebhook($input: CreateWebhookInput!) {
  createWebhook(input: $input) {
    events
    payloadFields
    id
    secret
    url
  }
}

# Update a bot webhook
mutation UpdateWebhook($input: UpdateWebhookInput!) {
  updateWebhook(input: $input) {
    events
    payloadFields
    id
    secret
    url
  }
}

# Sync a bot information
mutation SyncBotInformation($input: GetBotInput!) {
  syncBotInformation(input: $input) {
    name
  }
}

######################################
######                          ######
######           MISC           ######
######                          ######
######################################

# Logout...?
mutation Logout {
  logOut
}

# Create a session
mutation CreateSession($input: CreateSessionInput!) {
  createSession(input: $input) {
    access_token
    expires_in
    refresh_token
  }
}

# Create a vanity
mutation CreateVanity($input: CreateVanityInput!) {
  createVanity(input: $input) {
    id
    targetId
    type
    userId
  }
}